---
- name: Deploy PetClinic to Staging
  hosts: jenkins
  tasks:
    - name: Stop and remove existing staging container
      shell: |
        docker stop petclinic-staging || true
        docker rm petclinic-staging || true

    - name: Deploy staging container
      shell: |
        docker run -d \
          --name petclinic-staging \
          -p 8082:8080 \
          kastrel7/spring-petclinic:latest